name: MLB HRR Daily Update

on:
  schedule:
    - cron: "0 13,15,16,17,19,21,23 * * *"
  workflow_dispatch:

jobs:
  generate-hrr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'
      - name: Install dependencies
        run: npm install
        working-directory: scripts
      - name: Generate HRR data
        run: node generate-hrr.js || node generate-hrr.js
        working-directory: scripts
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
